#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v20
# autospec commit: a19cdc7
#
Name     : pypi-blosc
Version  : 1.11.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/0b/11/c684c09ac3f4e75691bfc7827dd23743bcf30b35751697278c614332700e/blosc-1.11.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/0b/11/c684c09ac3f4e75691bfc7827dd23743bcf30b35751697278c614332700e/blosc-1.11.2.tar.gz
Summary  : Blosc data compressor
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 MIT Zlib
Requires: pypi-blosc-lib = %{version}-%{release}
Requires: pypi-blosc-license = %{version}-%{release}
Requires: pypi-blosc-python = %{version}-%{release}
Requires: pypi-blosc-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : ninja
BuildRequires : pypi(ninja)
BuildRequires : pypi(numpy)
BuildRequires : pypi(py_cpuinfo)
BuildRequires : pypi(scikit_build)
BuildRequires : pypi(setuptools)
BuildRequires : pypi-cython
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
============
Python-Blosc
============
A Python wrapper for the extremely fast Blosc compression library
=================================================================

%package dev
Summary: dev components for the pypi-blosc package.
Group: Development
Requires: pypi-blosc-lib = %{version}-%{release}
Provides: pypi-blosc-devel = %{version}-%{release}
Requires: pypi-blosc = %{version}-%{release}

%description dev
dev components for the pypi-blosc package.


%package lib
Summary: lib components for the pypi-blosc package.
Group: Libraries
Requires: pypi-blosc-license = %{version}-%{release}

%description lib
lib components for the pypi-blosc package.


%package license
Summary: license components for the pypi-blosc package.
Group: Default

%description license
license components for the pypi-blosc package.


%package python
Summary: python components for the pypi-blosc package.
Group: Default
Requires: pypi-blosc-python3 = %{version}-%{release}

%description python
python components for the pypi-blosc package.


%package python3
Summary: python3 components for the pypi-blosc package.
Group: Default
Requires: python3-core
Provides: pypi(blosc)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-blosc package.


%package staticdev
Summary: staticdev components for the pypi-blosc package.
Group: Default
Requires: pypi-blosc-dev = %{version}-%{release}

%description staticdev
staticdev components for the pypi-blosc package.


%prep
%setup -q -n blosc-1.11.2
cd %{_builddir}/blosc-1.11.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729302676
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-blosc
cp %{_builddir}/blosc-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/1c7197315778beeed6290368ce5498f2eeb7dd57 || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/f95d3411831b0a3233ecbba99b85d2f1688773cd || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSES/BITSHUFFLE.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/d1b152dfd8ac42778f5d4aacfb62b92bf2ab4145 || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSES/FASTLZ.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/7f9f00bd71460bbd6551c361fe5e95023ab69ebd || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSES/SNAPPY.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/0d45aa696e5c82d8d1a1a1bbdc55d8e5fc328ccc || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSES/STDINT.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/257fcfb59f520ac78cf01eb575d07aacfbb41b37 || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/LICENSES/ZLIB.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/233f44af3fb55dcc7fddfef8e77ac627b0008756 || :
cp %{_builddir}/blosc-%{version}/blosc/c-blosc/internal-complibs/zlib-1.3.1/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/pypi-blosc/3f317fbb3e08fd99169d2e77105d562ea0e482c7 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/blosc-export.h
/usr/include/blosc.h
/usr/lib64/libblosc.so
/usr/lib64/pkgconfig/blosc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libblosc.so.1
/usr/lib64/libblosc.so.1.21.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-blosc/0d45aa696e5c82d8d1a1a1bbdc55d8e5fc328ccc
/usr/share/package-licenses/pypi-blosc/1c7197315778beeed6290368ce5498f2eeb7dd57
/usr/share/package-licenses/pypi-blosc/233f44af3fb55dcc7fddfef8e77ac627b0008756
/usr/share/package-licenses/pypi-blosc/257fcfb59f520ac78cf01eb575d07aacfbb41b37
/usr/share/package-licenses/pypi-blosc/3f317fbb3e08fd99169d2e77105d562ea0e482c7
/usr/share/package-licenses/pypi-blosc/7f9f00bd71460bbd6551c361fe5e95023ab69ebd
/usr/share/package-licenses/pypi-blosc/d1b152dfd8ac42778f5d4aacfb62b92bf2ab4145
/usr/share/package-licenses/pypi-blosc/f95d3411831b0a3233ecbba99b85d2f1688773cd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libblosc.a
